[package]
name = "golem-tts-google"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem-ai"
description = "WebAssembly component for working with Google APIs, with special support for Golem Cloud"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[features]
default = ["durability"]
durability = ["golem-rust/durability", "golem-tts/durability"]

[dependencies]
golem-tts = { workspace = true }

golem-rust = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = "0.7"
wit-bindgen-rt = { workspace = true }
base64 = { workspace = true }
sha2 = "0.10"
rsa = { version = "0.9", features = ["sha2"] }
wstd = { workspace = true }
rand = "0.8"
urlencoding = "2.1"


[dev-dependencies] 

[package.metadata.component]
package = "golem:tts-google"

[package.metadata.component.bindings]
generate_unused_types = true

[package.metadata.component.bindings.with]
"golem:tts/types@1.0.0" = "golem_tts::golem::tts::types"
"golem:tts/voices@1.0.0" = "golem_tts::golem::tts::voices"
"golem:tts/synthesis@1.0.0" = "golem_tts::golem::tts::synthesis"
"golem:tts/advanced@1.0.0" = "golem_tts::golem::tts::advanced"

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
"golem:tts" = { path = "wit/deps/golem-tts" }
"wasi:io" = { path = "wit/deps/io" }
